osm_data:
  image: debian:jessie
  # command: wget -O /var/data/osm-planet/pbf/planet-latest.osm.pbf http://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-latest.osm.pbf
  volumes:
    - /tmp/osm-planet:/var/data/osm-planet

osm_cache:
  image: debian:jessie
  volumes:
    - osm-world-db_osm_cache:/var/cache/osm-cache

postgis:
  image: geometalab/postgis:9.4
  volumes:
    - osm_world_db-postgis-data:/var/lib/postgresql
  environment:
    - POSTGRES_DB=gis
    - POSTGRES_USER=gis
    - POSTGRES_PASSWORD=gis

osm_importer:
  image: geometalab/osm2pgsql:latest
  # for development, disable the line above and uncomment the line below
  # build: .
  command: /root/update_db.sh
  links:
    - postgis:database
  volumes_from:
    - osm_data
    - osm_cache
