version: '2'
services:
  database:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: osmworlddb_postgis
    image: geometalab/postgis:9.5
    volumes:
      - database-postgis-data:/var/lib/postgresql
    command: postgres -B 12GB -F -N 512 -S 20GB --max_wal_size=5GB
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=gis
    logging:
      driver: "json-file"
      options:
        max-size: 50k
  osm_importer:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: osmworlddb_osm_importer
    image: geometalab/osm2pgsql:latest
    # for development, disable the line above and uncomment the line below
#    build: .
    entrypoint: /root/wait-for-it.sh database:5432 --
    command: /root/run.sh
    depends_on:
      - database
    volumes:
      - osm_data:/var/data/osm-planet
      - osm_cache:/var/cache/osm-cache
    environment:
      - num_processes=16
    logging:
      driver: "json-file"
      options:
        max-size: 50k
volumes:
  osm_data: {}
  osm_cache: {}
  database-postgis-data: {}
